# Generated by Django 4.0.6 on 2022-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('designation', models.TextField()),
                ('vendeur', models.CharField(max_length=50)),
                ('date_achat', models.DateField()),
                ('date_peremption', models.DateField()),
                ('prix', models.DecimalField(decimal_places=4, max_digits=5)),
                ('quantite', models.IntegerField()),
            ],
        ),
    ]
