# Generated by Django 4.0.6 on 2022-08-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
